// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: E:/Soft/Proje/LXCLUA/app/src/main/java/com/nirithy/luaeditor/tools/tokenizer/lua.flex

package com.nirithy.luaeditor.tools.tokenizer;

import static com.nirithy.luaeditor.tools.tokenizer.LuaTokenTypes.*;
import java.io.IOException;
import java.io.Reader;


@SuppressWarnings("fallthrough")
public class LuaLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int xSHEBANG = 2;
  public static final int xDOUBLE_QUOTED_STRING = 4;
  public static final int xSINGLE_QUOTED_STRING = 6;
  public static final int xBLOCK_STRING = 8;
  public static final int xBLOCK_COMMENT = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5, 5
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\10\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\2\37\1\41\1\37\11\42\1\43"+
    "\7\42\1\44\2\42\1\45\1\46\1\47\1\50\1\51"+
    "\1\0\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\42\1\63\1\64\1\65\1\66\1\67"+
    "\1\70\1\42\1\71\1\72\1\73\1\74\1\75\1\76"+
    "\1\77\1\100\1\42\1\101\1\102\1\103\1\104\6\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\2\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\23\32\1\36"+
    "\1\37\1\40\1\41\1\42\2\43\1\42\2\44\1\45"+
    "\1\0\1\42\2\44\1\0\3\46\1\0\1\47\1\0"+
    "\1\50\1\51\1\52\2\0\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\63\1\22\4\0\1\64"+
    "\1\65\1\66\1\67\1\70\1\71\1\72\1\73\1\74"+
    "\1\75\1\76\1\0\1\77\1\100\11\32\1\101\11\32"+
    "\1\102\1\32\1\103\1\104\10\32\1\105\14\32\1\106"+
    "\1\107\1\0\1\110\2\0\1\42\2\0\1\42\1\0"+
    "\1\111\1\0\1\112\1\56\1\113\3\56\1\114\1\115"+
    "\1\116\1\22\1\0\2\22\1\117\1\120\1\121\2\32"+
    "\1\122\1\123\10\32\1\124\5\32\1\125\7\32\1\126"+
    "\1\127\16\32\1\130\4\32\1\131\1\132\2\56\1\22"+
    "\3\32\1\133\7\32\1\134\1\135\6\32\1\136\5\32"+
    "\1\137\11\32\1\140\1\141\1\142\1\32\1\143\1\32"+
    "\1\144\2\56\3\0\1\32\1\145\1\146\1\147\1\32"+
    "\1\150\2\32\1\151\3\32\1\152\1\153\5\32\1\154"+
    "\12\32\1\155\1\156\2\56\1\157\1\160\4\32\1\161"+
    "\1\162\3\32\1\163\2\32\1\164\2\32\1\165\2\32"+
    "\1\166\1\167\1\170\1\171\1\172\2\56\1\32\1\173"+
    "\1\32\1\174\1\175\1\176\2\32\1\177\2\32\1\200"+
    "\1\32\1\56\1\201\1\202\1\203\1\204\2\32\1\205"+
    "\1\32\1\56\2\32\1\206\1\56\1\207\1\210\1\211";

  private static int [] zzUnpackAction() {
    int [] result = new int[374];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\105\0\212\0\317\0\u0114\0\u0159\0\u019e\0\u01e3"+
    "\0\u019e\0\u0228\0\u026d\0\u02b2\0\u019e\0\u02f7\0\u033c\0\u0381"+
    "\0\u019e\0\u019e\0\u03c6\0\u040b\0\u019e\0\u0450\0\u0495\0\u04da"+
    "\0\u051f\0\u0564\0\u05a9\0\u019e\0\u05ee\0\u0633\0\u0678\0\u06bd"+
    "\0\u019e\0\u0702\0\u0747\0\u019e\0\u078c\0\u07d1\0\u0816\0\u085b"+
    "\0\u08a0\0\u08e5\0\u092a\0\u096f\0\u09b4\0\u09f9\0\u0a3e\0\u0a83"+
    "\0\u0ac8\0\u0b0d\0\u0b52\0\u0b97\0\u0bdc\0\u0c21\0\u0c66\0\u0cab"+
    "\0\u019e\0\u0cf0\0\u019e\0\u0d35\0\u0d7a\0\u019e\0\u0dbf\0\u0e04"+
    "\0\u0e49\0\u0e8e\0\u019e\0\u0ed3\0\u0f18\0\u0f5d\0\u0fa2\0\u0fe7"+
    "\0\u102c\0\u1071\0\u10b6\0\u026d\0\u019e\0\u10fb\0\u019e\0\u019e"+
    "\0\u019e\0\u0381\0\u1140\0\u019e\0\u019e\0\u019e\0\u1185\0\u019e"+
    "\0\u019e\0\u11ca\0\u120f\0\u019e\0\u1254\0\u1299\0\u12de\0\u1323"+
    "\0\u1368\0\u019e\0\u019e\0\u13ad\0\u13f2\0\u019e\0\u019e\0\u019e"+
    "\0\u019e\0\u1437\0\u019e\0\u019e\0\u0747\0\u019e\0\u019e\0\u147c"+
    "\0\u14c1\0\u1506\0\u154b\0\u1590\0\u15d5\0\u161a\0\u165f\0\u16a4"+
    "\0\u0702\0\u16e9\0\u172e\0\u1773\0\u17b8\0\u17fd\0\u1842\0\u1887"+
    "\0\u18cc\0\u1911\0\u0702\0\u1956\0\u0702\0\u0702\0\u199b\0\u19e0"+
    "\0\u1a25\0\u1a6a\0\u1aaf\0\u1af4\0\u1b39\0\u1b7e\0\u0702\0\u1bc3"+
    "\0\u1c08\0\u1c4d\0\u1c92\0\u1cd7\0\u1d1c\0\u1d61\0\u1da6\0\u1deb"+
    "\0\u1e30\0\u1e75\0\u1eba\0\u019e\0\u019e\0\u1eff\0\u019e\0\u0e49"+
    "\0\u1f44\0\u0e49\0\u0f5d\0\u1f89\0\u0f5d\0\u1071\0\u019e\0\u10b6"+
    "\0\u019e\0\u1fce\0\u2013\0\u2058\0\u209d\0\u20e2\0\u019e\0\u019e"+
    "\0\u019e\0\u2127\0\u216c\0\u21b1\0\u21f6\0\u019e\0\u019e\0\u019e"+
    "\0\u223b\0\u2280\0\u0702\0\u0702\0\u22c5\0\u230a\0\u234f\0\u2394"+
    "\0\u23d9\0\u241e\0\u2463\0\u24a8\0\u0702\0\u24ed\0\u2532\0\u2577"+
    "\0\u25bc\0\u2601\0\u0702\0\u2646\0\u268b\0\u26d0\0\u2715\0\u275a"+
    "\0\u279f\0\u27e4\0\u0702\0\u0702\0\u2829\0\u286e\0\u28b3\0\u28f8"+
    "\0\u293d\0\u2982\0\u29c7\0\u2a0c\0\u2a51\0\u2a96\0\u2adb\0\u2b20"+
    "\0\u2b65\0\u2baa\0\u0702\0\u2bef\0\u2c34\0\u2c79\0\u2cbe\0\u019e"+
    "\0\u1fce\0\u2d03\0\u2d48\0\u2d8d\0\u2dd2\0\u2e17\0\u2e5c\0\u0702"+
    "\0\u2ea1\0\u2ee6\0\u2f2b\0\u2f70\0\u2fb5\0\u2ffa\0\u303f\0\u3084"+
    "\0\u0702\0\u30c9\0\u310e\0\u3153\0\u3198\0\u31dd\0\u3222\0\u0702"+
    "\0\u3267\0\u32ac\0\u32f1\0\u3336\0\u337b\0\u0702\0\u33c0\0\u3405"+
    "\0\u344a\0\u348f\0\u34d4\0\u3519\0\u355e\0\u35a3\0\u35e8\0\u0702"+
    "\0\u0702\0\u0702\0\u362d\0\u0702\0\u3672\0\u0702\0\u36b7\0\u36fc"+
    "\0\u3741\0\u3786\0\u37cb\0\u3810\0\u0702\0\u0702\0\u0702\0\u3855"+
    "\0\u0702\0\u389a\0\u38df\0\u0702\0\u3924\0\u3969\0\u39ae\0\u0702"+
    "\0\u39f3\0\u3a38\0\u3a7d\0\u3ac2\0\u3b07\0\u3b4c\0\u0702\0\u3b91"+
    "\0\u3bd6\0\u3c1b\0\u3c60\0\u3ca5\0\u3cea\0\u3d2f\0\u3d74\0\u3db9"+
    "\0\u3dfe\0\u0702\0\u0702\0\u3e43\0\u3e88\0\u019e\0\u019e\0\u3ecd"+
    "\0\u3f12\0\u3f57\0\u3f9c\0\u0702\0\u0702\0\u3fe1\0\u4026\0\u406b"+
    "\0\u0702\0\u40b0\0\u40f5\0\u0702\0\u413a\0\u417f\0\u0702\0\u41c4"+
    "\0\u4209\0\u0702\0\u0702\0\u0702\0\u0702\0\u0702\0\u424e\0\u4293"+
    "\0\u42d8\0\u0702\0\u431d\0\u0702\0\u0702\0\u0702\0\u4362\0\u43a7"+
    "\0\u0702\0\u43ec\0\u4431\0\u0702\0\u4476\0\u44bb\0\u4500\0\u0702"+
    "\0\u0702\0\u0702\0\u4545\0\u458a\0\u0702\0\u45cf\0\u4614\0\u4659"+
    "\0\u469e\0\u0702\0\u46e3\0\u0702\0\u0702\0\u4728";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[374];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\1\10\1\11\1\0\1\10\1\12\1\7\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\2\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\6\42\1\43"+
    "\1\7\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\42\1\56\1\57\1\60\1\42"+
    "\1\61\1\62\1\63\1\64\1\65\1\66\1\67\1\42"+
    "\1\70\2\42\1\71\1\72\1\73\1\74\2\75\1\76"+
    "\2\75\1\77\77\75\2\100\1\101\2\100\1\102\1\100"+
    "\1\103\36\100\1\104\36\100\2\105\1\106\2\105\1\107"+
    "\6\105\1\103\31\105\1\110\36\105\47\111\1\112\104\111"+
    "\1\113\35\111\106\0\1\10\2\0\1\10\102\0\1\11"+
    "\102\0\7\114\1\115\36\114\1\116\36\114\6\0\1\117"+
    "\131\0\1\120\104\0\1\121\51\0\14\122\1\115\31\122"+
    "\1\123\36\122\33\0\1\124\71\0\1\125\12\0\1\126"+
    "\73\0\1\127\10\0\1\130\1\131\73\0\1\132\105\0"+
    "\1\133\6\0\1\134\74\0\1\135\1\0\3\32\10\0"+
    "\1\136\1\137\2\0\1\140\4\0\1\141\1\0\1\136"+
    "\2\0\1\137\20\0\1\140\30\0\1\135\1\0\3\32"+
    "\11\0\1\137\7\0\1\141\4\0\1\137\56\0\1\142"+
    "\2\0\1\143\103\0\1\144\1\145\46\0\1\146\35\0"+
    "\1\147\1\150\103\0\1\151\1\152\73\0\1\153\11\0"+
    "\1\154\74\0\3\42\7\0\6\42\4\0\30\42\37\0"+
    "\1\155\11\0\1\156\72\0\1\157\76\0\3\42\7\0"+
    "\6\42\4\0\20\42\1\160\7\42\31\0\3\42\7\0"+
    "\6\42\4\0\2\42\1\161\12\42\1\162\3\42\1\163"+
    "\6\42\31\0\3\42\7\0\6\42\4\0\20\42\1\164"+
    "\7\42\31\0\3\42\7\0\6\42\4\0\1\42\1\165"+
    "\11\42\1\166\2\42\1\167\11\42\31\0\3\42\7\0"+
    "\6\42\4\0\5\42\1\170\10\42\1\171\11\42\31\0"+
    "\3\42\7\0\6\42\4\0\13\42\1\172\1\42\1\173"+
    "\10\42\1\174\1\42\31\0\3\42\7\0\6\42\4\0"+
    "\1\42\1\175\7\42\1\176\4\42\1\177\4\42\1\200"+
    "\4\42\31\0\3\42\7\0\6\42\4\0\13\42\1\201"+
    "\2\42\1\202\11\42\31\0\3\42\7\0\6\42\4\0"+
    "\6\42\1\203\5\42\1\204\1\205\3\42\1\206\6\42"+
    "\31\0\3\42\7\0\6\42\4\0\5\42\1\207\22\42"+
    "\31\0\3\42\7\0\6\42\4\0\1\42\1\210\14\42"+
    "\1\211\11\42\31\0\3\42\7\0\6\42\4\0\11\42"+
    "\1\212\4\42\1\213\11\42\31\0\3\42\7\0\6\42"+
    "\4\0\11\42\1\214\3\42\1\215\1\42\1\216\1\217"+
    "\1\220\6\42\31\0\3\42\7\0\6\42\4\0\20\42"+
    "\1\221\2\42\1\222\4\42\31\0\3\42\7\0\6\42"+
    "\4\0\5\42\1\223\22\42\31\0\3\42\7\0\6\42"+
    "\4\0\22\42\1\224\2\42\1\225\2\42\31\0\3\42"+
    "\7\0\6\42\4\0\1\42\1\226\6\42\1\227\7\42"+
    "\1\230\7\42\31\0\3\42\7\0\6\42\4\0\15\42"+
    "\1\231\12\42\31\0\3\42\7\0\6\42\4\0\10\42"+
    "\1\232\1\233\16\42\37\0\1\234\1\235\1\236\102\0"+
    "\1\237\51\0\2\75\1\0\2\75\1\0\77\75\2\0"+
    "\1\76\102\0\2\100\1\240\2\100\1\240\1\100\1\103"+
    "\36\100\1\241\36\100\7\240\1\103\36\240\1\241\40\240"+
    "\1\101\4\240\1\103\36\240\1\241\36\240\2\242\4\240"+
    "\77\242\2\105\1\243\2\105\1\243\6\105\1\103\31\105"+
    "\1\244\36\105\14\243\1\103\31\243\1\244\40\243\1\106"+
    "\11\243\1\103\31\243\1\244\36\243\2\245\4\243\77\245"+
    "\47\111\1\0\35\111\33\0\1\246\13\0\1\247\70\0"+
    "\1\250\13\0\1\251\35\0\105\114\105\122\2\252\1\0"+
    "\2\252\1\0\14\252\1\253\22\252\1\254\10\252\1\255"+
    "\12\252\1\256\13\252\23\0\1\257\7\0\1\260\104\0"+
    "\1\261\76\0\3\135\11\0\1\137\14\0\1\137\53\0"+
    "\2\262\76\0\1\263\1\0\1\263\2\0\3\264\102\0"+
    "\3\265\7\0\3\265\10\0\6\265\52\0\3\32\110\0"+
    "\1\266\105\0\1\267\103\0\1\270\76\0\3\42\7\0"+
    "\6\42\4\0\1\42\1\271\26\42\31\0\3\42\7\0"+
    "\6\42\4\0\21\42\1\272\6\42\31\0\3\42\7\0"+
    "\6\42\4\0\4\42\1\273\23\42\31\0\3\42\7\0"+
    "\6\42\4\0\14\42\1\274\13\42\31\0\3\42\7\0"+
    "\6\42\4\0\5\42\1\275\22\42\31\0\3\42\7\0"+
    "\6\42\4\0\21\42\1\276\1\277\5\42\31\0\3\42"+
    "\7\0\6\42\4\0\1\42\1\300\26\42\31\0\3\42"+
    "\7\0\6\42\4\0\14\42\1\301\1\302\12\42\31\0"+
    "\3\42\7\0\6\42\4\0\6\42\1\303\21\42\31\0"+
    "\3\42\7\0\6\42\4\0\21\42\1\304\6\42\31\0"+
    "\3\42\7\0\6\42\4\0\4\42\1\305\16\42\1\306"+
    "\4\42\31\0\3\42\7\0\6\42\4\0\17\42\1\307"+
    "\2\42\1\310\5\42\31\0\3\42\7\0\6\42\4\0"+
    "\13\42\1\311\14\42\31\0\3\42\7\0\6\42\4\0"+
    "\15\42\1\312\12\42\31\0\3\42\7\0\6\42\4\0"+
    "\20\42\1\313\7\42\31\0\3\42\7\0\6\42\4\0"+
    "\15\42\1\314\12\42\31\0\3\42\7\0\6\42\4\0"+
    "\16\42\1\315\11\42\31\0\3\42\7\0\6\42\4\0"+
    "\22\42\1\316\5\42\31\0\3\42\7\0\6\42\4\0"+
    "\17\42\1\317\10\42\31\0\3\42\7\0\6\42\4\0"+
    "\27\42\1\320\31\0\3\42\7\0\6\42\4\0\14\42"+
    "\1\321\13\42\31\0\3\42\7\0\6\42\4\0\3\42"+
    "\1\322\24\42\31\0\3\42\7\0\6\42\4\0\13\42"+
    "\1\323\14\42\31\0\3\42\7\0\6\42\4\0\22\42"+
    "\1\324\5\42\31\0\3\42\7\0\6\42\4\0\15\42"+
    "\1\325\12\42\31\0\3\42\7\0\6\42\4\0\5\42"+
    "\1\326\22\42\31\0\3\42\7\0\6\42\4\0\5\42"+
    "\1\327\22\42\31\0\3\42\7\0\6\42\4\0\23\42"+
    "\1\330\4\42\31\0\3\42\7\0\6\42\4\0\11\42"+
    "\1\331\4\42\1\332\11\42\31\0\3\42\7\0\6\42"+
    "\4\0\2\42\1\333\25\42\31\0\3\42\7\0\6\42"+
    "\4\0\17\42\1\334\2\42\1\335\5\42\31\0\3\42"+
    "\7\0\6\42\4\0\1\42\1\336\26\42\31\0\3\42"+
    "\7\0\6\42\4\0\11\42\1\337\16\42\31\0\3\42"+
    "\7\0\6\42\4\0\12\42\1\340\15\42\31\0\3\42"+
    "\7\0\6\42\4\0\5\42\1\341\22\42\31\0\3\42"+
    "\7\0\6\42\4\0\23\42\1\342\3\42\1\343\31\0"+
    "\3\42\7\0\6\42\4\0\22\42\1\344\5\42\31\0"+
    "\3\42\7\0\6\42\4\0\5\42\1\345\3\42\1\346"+
    "\16\42\31\0\3\42\7\0\6\42\4\0\22\42\1\347"+
    "\5\42\40\0\1\350\50\0\105\240\105\243\2\252\1\0"+
    "\2\252\1\0\77\252\2\253\1\0\2\253\1\0\77\253"+
    "\2\252\1\0\2\252\1\0\25\252\1\254\11\252\1\351"+
    "\41\252\1\0\2\252\1\0\60\252\1\352\20\252\1\0"+
    "\2\252\1\0\50\252\1\353\26\252\25\0\2\262\22\0"+
    "\1\136\60\0\3\264\102\0\3\264\21\0\1\263\56\0"+
    "\1\354\1\0\3\265\7\0\3\265\1\0\1\137\5\0"+
    "\1\140\6\265\10\0\1\137\41\0\3\42\7\0\6\42"+
    "\4\0\25\42\1\355\2\42\31\0\3\42\7\0\6\42"+
    "\4\0\22\42\1\356\5\42\31\0\3\42\7\0\6\42"+
    "\4\0\1\42\1\357\26\42\31\0\3\42\7\0\6\42"+
    "\4\0\5\42\1\360\22\42\31\0\3\42\7\0\6\42"+
    "\4\0\3\42\1\361\24\42\31\0\3\42\7\0\6\42"+
    "\4\0\21\42\1\362\6\42\31\0\3\42\7\0\6\42"+
    "\4\0\14\42\1\363\13\42\31\0\3\42\7\0\6\42"+
    "\4\0\21\42\1\364\1\365\5\42\31\0\3\42\7\0"+
    "\6\42\4\0\1\42\1\366\3\42\1\367\22\42\31\0"+
    "\3\42\7\0\6\42\4\0\5\42\1\370\22\42\31\0"+
    "\3\42\7\0\6\42\4\0\14\42\1\371\13\42\31\0"+
    "\3\42\7\0\6\42\4\0\16\42\1\372\11\42\31\0"+
    "\3\42\7\0\6\42\4\0\5\42\1\373\22\42\31\0"+
    "\3\42\7\0\6\42\4\0\21\42\1\374\6\42\31\0"+
    "\3\42\7\0\6\42\4\0\1\42\1\375\26\42\31\0"+
    "\3\42\7\0\6\42\4\0\3\42\1\376\24\42\31\0"+
    "\3\42\7\0\6\42\4\0\2\42\1\377\25\42\31\0"+
    "\3\42\7\0\6\42\4\0\16\42\1\u0100\11\42\31\0"+
    "\3\42\7\0\6\42\4\0\13\42\1\u0101\14\42\31\0"+
    "\3\42\7\0\6\42\4\0\25\42\1\u0102\2\42\31\0"+
    "\3\42\7\0\6\42\4\0\2\42\1\u0103\25\42\31\0"+
    "\3\42\7\0\6\42\4\0\1\42\1\u0104\26\42\31\0"+
    "\3\42\7\0\6\42\4\0\22\42\1\u0105\5\42\31\0"+
    "\3\42\7\0\6\42\4\0\25\42\1\u0106\2\42\31\0"+
    "\3\42\7\0\6\42\4\0\20\42\1\u0107\7\42\31\0"+
    "\3\42\7\0\6\42\4\0\17\42\1\u0108\10\42\31\0"+
    "\3\42\7\0\6\42\4\0\24\42\1\u0109\3\42\31\0"+
    "\3\42\7\0\6\42\4\0\22\42\1\u010a\5\42\31\0"+
    "\3\42\7\0\6\42\4\0\13\42\1\u010b\14\42\31\0"+
    "\3\42\7\0\6\42\4\0\5\42\1\u010c\22\42\31\0"+
    "\3\42\7\0\6\42\4\0\23\42\1\u010d\4\42\31\0"+
    "\3\42\7\0\6\42\4\0\22\42\1\u010e\5\42\31\0"+
    "\3\42\7\0\6\42\4\0\22\42\1\u010f\5\42\31\0"+
    "\3\42\7\0\6\42\4\0\5\42\1\u0110\22\42\31\0"+
    "\3\42\7\0\6\42\4\0\15\42\1\u0111\12\42\31\0"+
    "\3\42\7\0\6\42\4\0\5\42\1\u0112\22\42\31\0"+
    "\3\42\7\0\6\42\4\0\11\42\1\u0113\16\42\31\0"+
    "\3\42\7\0\6\42\4\0\15\42\1\u0114\12\42\31\0"+
    "\3\42\7\0\6\42\4\0\13\42\1\u0115\14\42\31\0"+
    "\3\42\7\0\6\42\4\0\10\42\1\u0116\17\42\4\0"+
    "\2\252\1\0\2\252\1\0\47\252\1\u0117\31\252\1\0"+
    "\2\252\1\0\52\252\1\u0118\24\252\25\0\3\354\7\0"+
    "\3\354\1\0\1\137\6\0\6\354\10\0\1\137\23\0"+
    "\1\u0119\4\0\1\u011a\10\0\3\42\7\0\6\42\1\u011b"+
    "\3\0\30\42\31\0\3\42\7\0\6\42\4\0\20\42"+
    "\1\u011c\7\42\31\0\3\42\7\0\6\42\4\0\12\42"+
    "\1\u011d\15\42\31\0\3\42\7\0\6\42\4\0\10\42"+
    "\1\u011e\17\42\31\0\3\42\7\0\6\42\4\0\21\42"+
    "\1\u011f\6\42\31\0\3\42\7\0\6\42\4\0\1\42"+
    "\1\u0120\26\42\31\0\3\42\7\0\6\42\4\0\22\42"+
    "\1\u0121\5\42\31\0\3\42\7\0\6\42\4\0\11\42"+
    "\1\u0122\16\42\31\0\3\42\7\0\6\42\4\0\23\42"+
    "\1\u0123\4\42\31\0\3\42\7\0\6\42\4\0\20\42"+
    "\1\u0124\7\42\31\0\3\42\7\0\6\42\4\0\11\42"+
    "\1\u0125\16\42\31\0\3\42\7\0\6\42\4\0\20\42"+
    "\1\u0126\7\42\31\0\3\42\7\0\6\42\4\0\15\42"+
    "\1\u0127\12\42\31\0\3\42\7\0\6\42\4\0\5\42"+
    "\1\u0128\22\42\31\0\3\42\7\0\6\42\4\0\13\42"+
    "\1\u0129\14\42\31\0\3\42\7\0\6\42\4\0\22\42"+
    "\1\u012a\5\42\31\0\3\42\7\0\6\42\4\0\1\42"+
    "\1\u012b\26\42\31\0\3\42\7\0\6\42\4\0\5\42"+
    "\1\u012c\22\42\31\0\3\42\7\0\6\42\4\0\16\42"+
    "\1\u012d\11\42\31\0\3\42\7\0\6\42\4\0\4\42"+
    "\1\u012e\23\42\31\0\3\42\7\0\6\42\4\0\13\42"+
    "\1\u012f\14\42\31\0\3\42\7\0\6\42\4\0\5\42"+
    "\1\u0130\22\42\31\0\3\42\7\0\6\42\4\0\1\42"+
    "\1\u0131\26\42\31\0\3\42\7\0\6\42\4\0\5\42"+
    "\1\u0132\22\42\31\0\3\42\7\0\6\42\4\0\1\42"+
    "\1\u0133\26\42\31\0\3\42\7\0\6\42\4\0\5\42"+
    "\1\u0134\22\42\31\0\3\42\7\0\6\42\4\0\11\42"+
    "\1\u0135\16\42\31\0\3\42\7\0\6\42\4\0\1\42"+
    "\1\u0136\26\42\31\0\3\42\7\0\6\42\4\0\20\42"+
    "\1\u0137\7\42\31\0\3\42\7\0\6\42\4\0\11\42"+
    "\1\u0138\16\42\31\0\3\42\7\0\6\42\4\0\3\42"+
    "\1\u0139\24\42\31\0\3\42\7\0\6\42\4\0\13\42"+
    "\1\u013a\14\42\31\0\3\42\7\0\6\42\4\0\5\42"+
    "\1\u013b\22\42\4\0\2\252\1\0\2\252\1\0\63\252"+
    "\1\u013c\15\252\1\0\2\252\1\0\54\252\1\u013d\22\252"+
    "\7\u0119\1\u013e\75\u0119\14\u011a\1\u013e\70\u011a\33\0\1\u011b"+
    "\11\0\1\u013f\64\0\3\42\7\0\6\42\4\0\1\42"+
    "\1\u0140\26\42\31\0\3\42\7\0\6\42\4\0\15\42"+
    "\1\u0141\12\42\31\0\3\42\7\0\6\42\4\0\15\42"+
    "\1\u0142\12\42\31\0\3\42\7\0\6\42\4\0\13\42"+
    "\1\u0143\14\42\31\0\3\42\7\0\6\42\4\0\6\42"+
    "\1\u0144\21\42\31\0\3\42\7\0\6\42\4\0\22\42"+
    "\1\u0145\5\42\31\0\3\42\7\0\6\42\4\0\4\42"+
    "\1\u0146\23\42\31\0\3\42\7\0\6\42\4\0\13\42"+
    "\1\u0147\14\42\31\0\3\42\7\0\6\42\4\0\11\42"+
    "\1\u0148\16\42\31\0\3\42\7\0\6\42\4\0\13\42"+
    "\1\u0149\14\42\31\0\3\42\7\0\6\42\4\0\14\42"+
    "\1\u014a\13\42\31\0\3\42\7\0\6\42\4\0\20\42"+
    "\1\u014b\7\42\31\0\3\42\7\0\6\42\4\0\1\42"+
    "\1\u014c\26\42\31\0\3\42\7\0\6\42\4\0\20\42"+
    "\1\u014d\7\42\31\0\3\42\7\0\6\42\4\0\22\42"+
    "\1\u014e\5\42\31\0\3\42\7\0\6\42\4\0\20\42"+
    "\1\u014f\7\42\31\0\3\42\7\0\6\42\4\0\22\42"+
    "\1\u0150\5\42\31\0\3\42\7\0\6\42\4\0\3\42"+
    "\1\u0151\24\42\31\0\3\42\7\0\6\42\4\0\3\42"+
    "\1\u0152\24\42\31\0\3\42\7\0\6\42\4\0\22\42"+
    "\1\u0153\5\42\31\0\3\42\7\0\6\42\4\0\15\42"+
    "\1\u0154\12\42\31\0\3\42\7\0\6\42\4\0\3\42"+
    "\1\u0155\24\42\31\0\3\42\7\0\6\42\4\0\10\42"+
    "\1\u0156\17\42\4\0\2\252\1\0\2\252\1\0\50\252"+
    "\1\u0157\30\252\1\0\2\252\1\0\61\252\1\u0158\15\252"+
    "\25\0\3\42\7\0\6\42\4\0\3\42\1\u0159\24\42"+
    "\31\0\3\42\7\0\6\42\4\0\4\42\1\u015a\23\42"+
    "\31\0\3\42\7\0\6\42\4\0\23\42\1\u015b\4\42"+
    "\31\0\3\42\7\0\6\42\4\0\22\42\1\u015c\5\42"+
    "\31\0\3\42\7\0\6\42\4\0\21\42\1\u015d\6\42"+
    "\31\0\3\42\7\0\6\42\4\0\27\42\1\u015e\31\0"+
    "\3\42\7\0\6\42\4\0\16\42\1\u015f\11\42\31\0"+
    "\3\42\7\0\6\42\4\0\5\42\1\u0160\22\42\31\0"+
    "\3\42\7\0\6\42\4\0\4\42\1\u0161\23\42\31\0"+
    "\3\42\7\0\6\42\4\0\6\42\1\u0162\21\42\31\0"+
    "\3\42\7\0\6\42\4\0\16\42\1\u0163\11\42\31\0"+
    "\3\42\7\0\6\42\4\0\5\42\1\u0164\22\42\31\0"+
    "\3\42\7\0\6\42\4\0\22\42\1\u0165\5\42\4\0"+
    "\2\252\1\0\2\252\1\0\52\252\1\u0166\26\252\1\0"+
    "\2\252\1\0\60\252\1\u0167\16\252\25\0\3\42\7\0"+
    "\6\42\4\0\22\42\1\u0168\5\42\31\0\3\42\7\0"+
    "\6\42\4\0\5\42\1\u0169\22\42\31\0\3\42\7\0"+
    "\6\42\4\0\15\42\1\u016a\12\42\31\0\3\42\7\0"+
    "\6\42\4\0\15\42\1\u016b\12\42\31\0\3\42\7\0"+
    "\6\42\4\0\1\42\1\u016c\26\42\31\0\3\42\7\0"+
    "\6\42\4\0\20\42\1\u016d\7\42\31\0\3\42\7\0"+
    "\6\42\4\0\5\42\1\u016e\22\42\4\0\2\252\1\0"+
    "\2\252\1\0\54\252\1\u016f\22\252\2\u0167\1\0\2\u0167"+
    "\1\0\77\u0167\25\0\3\42\7\0\6\42\4\0\22\42"+
    "\1\u0170\5\42\31\0\3\42\7\0\6\42\4\0\3\42"+
    "\1\u0171\24\42\31\0\3\42\7\0\6\42\4\0\4\42"+
    "\1\u0172\23\42\4\0\2\252\1\0\2\252\1\0\61\252"+
    "\1\u0173\15\252\25\0\3\42\7\0\6\42\4\0\21\42"+
    "\1\u0174\6\42\31\0\3\42\7\0\6\42\4\0\5\42"+
    "\1\u0175\22\42\4\0\2\252\1\0\2\252\1\0\60\252"+
    "\1\u0176\16\252\2\u0176\1\0\2\u0176\1\0\77\u0176";

  private static int [] zzUnpacktrans() {
    int [] result = new int[18285];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\11\1\1\1\11\3\1\1\11\3\1\2\11"+
    "\2\1\1\11\6\1\1\11\4\1\1\11\2\1\1\11"+
    "\24\1\1\11\1\1\1\11\2\1\1\11\4\1\1\11"+
    "\1\0\3\1\1\0\3\1\1\0\1\11\1\0\3\11"+
    "\2\0\3\11\1\1\2\11\2\1\1\11\1\1\4\0"+
    "\2\11\2\1\4\11\1\1\2\11\1\0\2\11\54\1"+
    "\2\11\1\0\1\11\2\0\1\1\2\0\1\1\1\0"+
    "\1\11\1\0\1\11\5\1\3\11\1\1\1\0\2\1"+
    "\3\11\57\1\1\11\60\1\3\0\42\1\2\11\67\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[374];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */

  /**
   * CharSequence 适配器，用于从 CharSequence 读取字符
   */
  static class CharSeqReader extends Reader
  {
    int offset = 0;
    CharSequence src;

    CharSeqReader(CharSequence src)
    {
      this.src = src;
    }

    @Override
    public void close() throws IOException
    {
      src = null;
      offset = 0;
    }

    @Override
    public int read(char[] chars, int i, int i1) throws IOException
    {
      int len = Math.min(src.length() - offset, i1);
      for (int n = 0; n < len; n++)
      {
        try{
          char c = src.charAt(offset++);
          chars[i++] = c;
        }catch(Exception e){
          // ignore
        }
      }
      if (len <= 0)
        return -1;
      return len;
    }
  }

  /**
   * 从 CharSequence 创建词法分析器
   */
  public LuaLexer(CharSequence src) {
    this(new CharSeqReader(src));
  }

  /**
   * 获取当前行号
   */
  public int yyline(){
    return yyline;
  }
  
  /**
   * 获取当前列号
   */
  public int yycolumn(){
    return yycolumn;
  }
  
  /**
   * 获取当前字符位置
   */
  public int yychar(){
    return (int)yychar;
  }
  
  // 块字符串/注释的等号数量
  private int nBrackets = 0;
  // 块内容缓冲区
  private StringBuilder blockBuffer = new StringBuilder();
  // 块开始标记
  private String blockStart = "";
  // 用于存储完整的块内容（开始标记 + 内容 + 结束标记）
  private String fullBlockContent = "";
  
  /**
   * 检查指定偏移处是否为指定字符
   */
  private boolean checkAhead(char c, int offset) {
    int pos = this.zzMarkedPos + offset;
    return pos < this.zzBuffer.length && this.zzBuffer[pos] == c;
  }

  /**
   * 检查并解析块字符串/注释的开始标记 [=*[
   * 设置 nBrackets 为等号数量
   * @return 是否是有效的块开始标记
   */
  private boolean checkBlock() {
    nBrackets = 0;
    if (checkAhead('[', 0)) {
      int n = 0;
      while (checkAhead('=', n + 1)) n++;
      if (checkAhead('[', n + 1)) {
        nBrackets = n;
        return true;
      }
    }
    return false;
  }

  /**
   * 从当前匹配文本中解析块开始标记的等号数量
   * 用于 [[, [=[, [==[, 等形式
   */
  private void parseBlockBrackets() {
    String text = yytext();
    nBrackets = 0;
    for (int i = 1; i < text.length() - 1; i++) {
      if (text.charAt(i) == '=') nBrackets++;
    }
  }

  /**
   * 检查块字符串/注释是否已闭合
   * @return 闭合标记后多余的字符数，-1 表示未闭合
   */
  private int checkBlockEnd() {
    String cs = blockBuffer.toString();
    StringBuilder closer = new StringBuilder("]");
    for (int i = 0; i < nBrackets; i++) closer.append('=');
    closer.append(']');
    int index = cs.indexOf(closer.toString());
    if (index >= 0) {
      return cs.length() - index - nBrackets - 2;
    }
    return -1;
  }

  /**
   * 获取完整的块内容（长字符串或块注释）
   * 包含开始标记、内容和结束标记
   * @return 完整的块内容
   */
  public String getBlockContent() {
    return fullBlockContent;
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LuaLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public LuaTokenTypes advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case xSHEBANG: {
              yybegin(YYINITIAL); return SHEBANG_CONTENT;
            }  // fall though
            case 375: break;
            case xDOUBLE_QUOTED_STRING: {
              yybegin(YYINITIAL); return BAD_CHARACTER;
            }  // fall though
            case 376: break;
            case xSINGLE_QUOTED_STRING: {
              yybegin(YYINITIAL); return BAD_CHARACTER;
            }  // fall though
            case 377: break;
            case xBLOCK_STRING: {
              fullBlockContent = blockStart + blockBuffer.toString();
                              yybegin(YYINITIAL); 
                              return BAD_CHARACTER;
            }  // fall though
            case 378: break;
            case xBLOCK_COMMENT: {
              fullBlockContent = blockStart + blockBuffer.toString();
                              yybegin(YYINITIAL); 
                              return BLOCK_COMMENT;
            }  // fall though
            case 379: break;
            default:
              {
                return null;
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return BAD_CHARACTER;
            }
          // fall through
          case 138: break;
          case 2:
            { return WHITE_SPACE;
            }
          // fall through
          case 139: break;
          case 3:
            { return NEW_LINE;
            }
          // fall through
          case 140: break;
          case 4:
            { yybegin(xDOUBLE_QUOTED_STRING);
            }
          // fall through
          case 141: break;
          case 5:
            { return GETN;
            }
          // fall through
          case 142: break;
          case 6:
            { return DOLLAR;
            }
          // fall through
          case 143: break;
          case 7:
            { return MOD;
            }
          // fall through
          case 144: break;
          case 8:
            { return BIT_AND;
            }
          // fall through
          case 145: break;
          case 9:
            { yybegin(xSINGLE_QUOTED_STRING);
            }
          // fall through
          case 146: break;
          case 10:
            { return LPAREN;
            }
          // fall through
          case 147: break;
          case 11:
            { return RPAREN;
            }
          // fall through
          case 148: break;
          case 12:
            { return MULT;
            }
          // fall through
          case 149: break;
          case 13:
            { return PLUS;
            }
          // fall through
          case 150: break;
          case 14:
            { return COMMA;
            }
          // fall through
          case 151: break;
          case 15:
            { return MINUS;
            }
          // fall through
          case 152: break;
          case 16:
            { return DOT;
            }
          // fall through
          case 153: break;
          case 17:
            { return DIV;
            }
          // fall through
          case 154: break;
          case 18:
            { return NUMBER;
            }
          // fall through
          case 155: break;
          case 19:
            { return COLON;
            }
          // fall through
          case 156: break;
          case 20:
            { return SEMI;
            }
          // fall through
          case 157: break;
          case 21:
            { return LT;
            }
          // fall through
          case 158: break;
          case 22:
            { return ASSIGN;
            }
          // fall through
          case 159: break;
          case 23:
            { return GT;
            }
          // fall through
          case 160: break;
          case 24:
            { return QUESTION;
            }
          // fall through
          case 161: break;
          case 25:
            { return AT;
            }
          // fall through
          case 162: break;
          case 26:
            { return NAME;
            }
          // fall through
          case 163: break;
          case 27:
            { return LBRACK;
            }
          // fall through
          case 164: break;
          case 28:
            { return RBRACK;
            }
          // fall through
          case 165: break;
          case 29:
            { return EXP;
            }
          // fall through
          case 166: break;
          case 30:
            { return LCURLY;
            }
          // fall through
          case 167: break;
          case 31:
            { return BIT_OR;
            }
          // fall through
          case 168: break;
          case 32:
            { return RCURLY;
            }
          // fall through
          case 169: break;
          case 33:
            { return BIT_TILDE;
            }
          // fall through
          case 170: break;
          case 34:
            { 
            }
          // fall through
          case 171: break;
          case 35:
            { yybegin(YYINITIAL); return SHEBANG_CONTENT;
            }
          // fall through
          case 172: break;
          case 36:
            { yybegin(YYINITIAL); return BAD_CHARACTER;
            }
          // fall through
          case 173: break;
          case 37:
            { yybegin(YYINITIAL); return STRING;
            }
          // fall through
          case 174: break;
          case 38:
            { blockBuffer.append(yytext());
            }
          // fall through
          case 175: break;
          case 39:
            { return STRING;
            }
          // fall through
          case 176: break;
          case 40:
            { yybegin(xSHEBANG); return SHEBANG;
            }
          // fall through
          case 177: break;
          case 41:
            { return MODEQ;
            }
          // fall through
          case 178: break;
          case 42:
            { return BANDEQ;
            }
          // fall through
          case 179: break;
          case 43:
            { return MULEQ;
            }
          // fall through
          case 180: break;
          case 44:
            { return PLUSPLUS;
            }
          // fall through
          case 181: break;
          case 45:
            { return ADDEQ;
            }
          // fall through
          case 182: break;
          case 46:
            { return SHORT_COMMENT;
            }
          // fall through
          case 183: break;
          case 47:
            { return SUBEQ;
            }
          // fall through
          case 184: break;
          case 48:
            { return LEF;
            }
          // fall through
          case 185: break;
          case 49:
            { return CONCAT;
            }
          // fall through
          case 186: break;
          case 50:
            { return DOUBLE_DIV;
            }
          // fall through
          case 187: break;
          case 51:
            { return DIVEQ;
            }
          // fall through
          case 188: break;
          case 52:
            { return DOUBLE_COLON;
            }
          // fall through
          case 189: break;
          case 53:
            { return WALRUS;
            }
          // fall through
          case 190: break;
          case 54:
            { return BIT_LTLT;
            }
          // fall through
          case 191: break;
          case 55:
            { return LE;
            }
          // fall through
          case 192: break;
          case 56:
            { return REVPIPE;
            }
          // fall through
          case 193: break;
          case 57:
            { return EQ;
            }
          // fall through
          case 194: break;
          case 58:
            { return MEAN;
            }
          // fall through
          case 195: break;
          case 59:
            { return GE;
            }
          // fall through
          case 196: break;
          case 60:
            { return BIT_RTRT;
            }
          // fall through
          case 197: break;
          case 61:
            { return OPTCHAIN;
            }
          // fall through
          case 198: break;
          case 62:
            { return NULLCOAL;
            }
          // fall through
          case 199: break;
          case 63:
            { blockStart = yytext();
                              parseBlockBrackets();
                              blockBuffer.setLength(0);
                              yybegin(xBLOCK_STRING);
            }
          // fall through
          case 200: break;
          case 64:
            { return BXOREQ;
            }
          // fall through
          case 201: break;
          case 65:
            { return DO;
            }
          // fall through
          case 202: break;
          case 66:
            { return IF;
            }
          // fall through
          case 203: break;
          case 67:
            { return IN;
            }
          // fall through
          case 204: break;
          case 68:
            { return IS;
            }
          // fall through
          case 205: break;
          case 69:
            { return OR;
            }
          // fall through
          case 206: break;
          case 70:
            { return BOREQ;
            }
          // fall through
          case 207: break;
          case 71:
            { return PIPE;
            }
          // fall through
          case 208: break;
          case 72:
            { return NE;
            }
          // fall through
          case 209: break;
          case 73:
            { String text = yytext();
                              int eqs = text.length() - 2;
                              blockBuffer.append(text);
                              if (eqs == nBrackets) {
                                fullBlockContent = blockStart + blockBuffer.toString();
                                yybegin(YYINITIAL);
                                return LONG_STRING;
                              }
            }
          // fall through
          case 210: break;
          case 74:
            { String text = yytext();
                              int eqs = text.length() - 2;
                              blockBuffer.append(text);
                              if (eqs == nBrackets) {
                                fullBlockContent = blockStart + blockBuffer.toString();
                                yybegin(YYINITIAL);
                                return BLOCK_COMMENT;
                              }
            }
          // fall through
          case 211: break;
          case 75:
            { return DOC_COMMENT;
            }
          // fall through
          case 212: break;
          case 76:
            { return ELLIPSIS;
            }
          // fall through
          case 213: break;
          case 77:
            { return CONCATEQ;
            }
          // fall through
          case 214: break;
          case 78:
            { return IDIVEQ;
            }
          // fall through
          case 215: break;
          case 79:
            { return SHLEQ;
            }
          // fall through
          case 216: break;
          case 80:
            { return SPACESHIP;
            }
          // fall through
          case 217: break;
          case 81:
            { return SHREQ;
            }
          // fall through
          case 218: break;
          case 82:
            { return AND;
            }
          // fall through
          case 219: break;
          case 83:
            { return ASM;
            }
          // fall through
          case 220: break;
          case 84:
            { return END;
            }
          // fall through
          case 221: break;
          case 85:
            { return FOR;
            }
          // fall through
          case 222: break;
          case 86:
            { return NIL;
            }
          // fall through
          case 223: break;
          case 87:
            { return NOT;
            }
          // fall through
          case 224: break;
          case 88:
            { return TRY;
            }
          // fall through
          case 225: break;
          case 89:
            { return SAFEPIPE;
            }
          // fall through
          case 226: break;
          case 90:
            { blockStart = yytext();
                              nBrackets = 0;
                              for (int i = 3; i < blockStart.length() - 1; i++) {
                                if (blockStart.charAt(i) == '=') nBrackets++;
                              }
                              blockBuffer.setLength(0);
                              yybegin(xBLOCK_COMMENT);
            }
          // fall through
          case 227: break;
          case 91:
            { return CASE;
            }
          // fall through
          case 228: break;
          case 92:
            { return ELSE;
            }
          // fall through
          case 229: break;
          case 93:
            { return ENUM;
            }
          // fall through
          case 230: break;
          case 94:
            { return GOTO;
            }
          // fall through
          case 231: break;
          case 95:
            { return NEW;
            }
          // fall through
          case 232: break;
          case 96:
            { return TAKE;
            }
          // fall through
          case 233: break;
          case 97:
            { return THEN;
            }
          // fall through
          case 234: break;
          case 98:
            { return TRUE;
            }
          // fall through
          case 235: break;
          case 99:
            { return WHEN;
            }
          // fall through
          case 236: break;
          case 100:
            { return WITH;
            }
          // fall through
          case 237: break;
          case 101:
            { return BREAK;
            }
          // fall through
          case 238: break;
          case 102:
            { return CATCH;
            }
          // fall through
          case 239: break;
          case 103:
            { return CLASS;
            }
          // fall through
          case 240: break;
          case 104:
            { return CONST;
            }
          // fall through
          case 241: break;
          case 105:
            { return DEFER;
            }
          // fall through
          case 242: break;
          case 106:
            { return FALSE;
            }
          // fall through
          case 243: break;
          case 107:
            { return FINAL;
            }
          // fall through
          case 244: break;
          case 108:
            { return LOCAL;
            }
          // fall through
          case 245: break;
          case 109:
            { return UNTIL;
            }
          // fall through
          case 246: break;
          case 110:
            { return WHILE;
            }
          // fall through
          case 247: break;
          case 111:
            { return RAW_STRING;
            }
          // fall through
          case 248: break;
          case 112:
            { blockStart = yytext();
                              nBrackets = 0;
                              for (int i = 2; i < blockStart.length() - 1; i++) {
                                if (blockStart.charAt(i) == '=') nBrackets++;
                              }
                              blockBuffer.setLength(0);
                              yybegin(xBLOCK_STRING);
            }
          // fall through
          case 249: break;
          case 113:
            { return ELSEIF;
            }
          // fall through
          case 250: break;
          case 114:
            { return EXPORT;
            }
          // fall through
          case 251: break;
          case 115:
            { return GLOBAL;
            }
          // fall through
          case 252: break;
          case 116:
            { return LAMBDA;
            }
          // fall through
          case 253: break;
          case 117:
            { return SUPER;
            }
          // fall through
          case 254: break;
          case 118:
            { return PUBLIC;
            }
          // fall through
          case 255: break;
          case 119:
            { return REPEAT;
            }
          // fall through
          case 256: break;
          case 120:
            { return RETURN;
            }
          // fall through
          case 257: break;
          case 121:
            { return STATIC;
            }
          // fall through
          case 258: break;
          case 122:
            { return SWITCH;
            }
          // fall through
          case 259: break;
          case 123:
            { return COMMAND;
            }
          // fall through
          case 260: break;
          case 124:
            { return DEFAULT;
            }
          // fall through
          case 261: break;
          case 125:
            { return EXTENDS;
            }
          // fall through
          case 262: break;
          case 126:
            { return FINALLY;
            }
          // fall through
          case 263: break;
          case 127:
            { return KEYWORD;
            }
          // fall through
          case 264: break;
          case 128:
            { return PRIVATE;
            }
          // fall through
          case 265: break;
          case 129:
            { return REGION;
            }
          // fall through
          case 266: break;
          case 130:
            { return ABSTRACT;
            }
          // fall through
          case 267: break;
          case 131:
            { return CONTINUE;
            }
          // fall through
          case 268: break;
          case 132:
            { return FUNCTION;
            }
          // fall through
          case 269: break;
          case 133:
            { return OPERATOR_KW;
            }
          // fall through
          case 270: break;
          case 134:
            { return PROTECTED;
            }
          // fall through
          case 271: break;
          case 135:
            { return IMPLEMENTS;
            }
          // fall through
          case 272: break;
          case 136:
            { return INTERFACE;
            }
          // fall through
          case 273: break;
          case 137:
            { return ENDREGION;
            }
          // fall through
          case 274: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
